
export const TOMAR_INCIDENCIAS = "TOMAR_INCIDENCIAS";
export const GUARDAR_INCIDENCIAS = "GUARDAR_INCIDENCIAS";
export const GUARDAR_INCIDENCIAS_ORIGINALS = "GUARDAR_INCIDENCIAS_ORIGINALS";
export const GUARDAR_INCIDENCIA_REDUX = "GUARDAR_INCIDENCIA_REDUX";
export const GUARDAR_ARCHIVO = "GUARDAR_ARCHIVO";
export const GUARDAR_CREADA = "GUARDAR_CREADA";