// export const ADD_TASK = "ADD_TASK";
// export const DELETE_TASK = "DELETE_TASK";
// export const DID_TASK = "DID_TASK";

export const GUARDAR_TOKEN = "GUARDAR_TOKEN";
export const GUARDAR_USUARIO = "GUARDAR_USUARIO";
export const GUARDAR_ARCHIVO = "GUARDAR_ARCHIVO";
export const GUARDAR_CREADA = "GUARDAR_CREADA";
export const GUARDAR_INCIDENCIA_REDUX = "GUARDAR_INCIDENCIA_REDUX";
export const GUARDAR_FILTROS = "GUARDAR_FILTROS";
export const GUARDAR_FILTROS_ORIGINALS = "GUARDAR_FILTROS_ORIGINALS";
export const SET_FAVORITO = "SET_FAVORITO";
export const INITIAL_FAVORITOS = "INITIAL_FAVORITOS";
export const GUARDAR_MARCADOS = "GUARDAR_MARCADOS";
export const GUARDAR_MARCADOS_ARRAY = "GUARDAR_MARCADOS_ARRAY";
export const GUARDAR_MARCADOS_ORIGINALS = "GUARDAR_MARCADOS_ORIGINALS";
export const GUARDAR_SECCIONES_PERFIL = "GUARDAR_SECCIONES_PERFIL";
export const TOMAR_TOKEN = "TOMAR_TOKEN";